# Generated by Django 6.0.5 on 2026-05-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('co2', models.IntegerField()),
                ('iluminacion', models.FloatField()),
                ('ruido', models.FloatField()),
                ('movimiento', models.BooleanField(default=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
