# Generated by Django 6.0.5 on 2026-05-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionambiental',
            name='aula',
            field=models.CharField(default='Aula de prueba', max_length=100),
        ),
        migrations.AddField(
            model_name='medicionambiental',
            name='nodo',
            field=models.CharField(default='nodo_01', max_length=50),
        ),
    ]
